### ISSUE TITLE
Can't clone 

### ISSUE THREAD

**Issue by journeytosilius** [tomek-szczesny/notcurses-vt-proto#1]
Do you pretend me to work on the repo straight ?  Cause I can't clone it ... let me know

```
xavier@xavierbcn:~$ git clone git@github.com:tomek-szczesny/notcurses-vt-proto.git
Cloning into 'notcurses-vt-proto'...
The authenticity of host 'github.com (140.82.121.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,140.82.121.3' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by tomek-szczesny** [comment]
Yeah, that's the idea, the file is yours to play with and as a collaborator you should have write access.

I think this is not a problem with the repo - if you can browse it online that means you should be able to clone it. It's a public repository after all.

As the error message says, there is something wrong with your authentication to github.

**Comment by tomek-szczesny** [comment]
Try cloning via https:
`git clone https://github.com/tomek-szczesny/notcurses-vt-proto.git`

Otherwise, there are some tips in github help:
https://docs.github.com/en/github/authenticating-to-github/troubleshooting-ssh/error-permission-denied-publickey

**Comment by journeytosilius** [comment]
weird ... I can clone other repos ...

**Comment by journeytosilius** [comment]
ok got it now
