### ISSUE TITLE
Switch efforts to VT widget

### ISSUE THREAD

**Issue by tomek-szczesny** [tomek-szczesny/notcurses-vt-proto#14]
I don't know what to make out of [Maintainer's response](https://github.com/dankamongmen/notcurses/discussions/1893#discussioncomment-989465), and my best guess is he doesn't have anything against "widgetizing" the whole VT thing.

I need to examine the widget code, but my best bet is that this should enable much more flexibility than screwing around with state-holding structs.

This may be a good opportunity to clean up everything (yet again).

This probably should happen before implementing alternative and scrollback buffers.

And the question is can I keep it outside the library for now, or should I work on a notcurses fork and deal with conflicts every day?

**Comment by tomek-szczesny** [comment]
Hm, should probably start by defining ncvt struct, and create/destroy methods. How fortunate, that will help me manage all that mess created to tip top around ncplane.

Looking at [progbar](https://github.com/dankamongmen/notcurses/blob/master/src/lib/progbar.c) code as a reference. Progress bar IS a widget, right?

**Comment by tomek-szczesny** [comment]
```
// Takes ownership of the ncplane 'n', which will be destroyed by
// ncprogbar_destroy(). The progress bar is initially at 0%.
API ALLOC struct ncprogbar* ncprogbar_create(struct ncplane* n, const ncprogbar_options* opts)
  __attribute__ ((nonnull (1)));
```

What on earth are all these fringes around it?

**Comment by joseluis** [comment]
> Looking at [progbar](https://github.com/dankamongmen/notcurses/blob/master/src/lib/progbar.c) code as a reference. Progress bar IS a widget, right?

Yes, it is.

> What on earth are all these fringes around it?

It you tag @dankamongmen he can probably can answer you better, since I'm not a C guy but:

- `API`

This indicates that will be exported as part of the public API. Goes before the return type signature.

- `ALLOC struct ncprogbar*`

This is the return type signature (in this caise a pointer to an allocated ncprogbar struct).

- `__attribute__ ((nonnull (1)))`

This is an attribute for compiler optimization. I think you can ignore that, since those can be added later if necessary.

**Comment by tomek-szczesny** [comment]
Thanks a lot! Now at least I know how to duckduckgo all that stuff. :)

I don't think I'd ask anybody specifically to teach me C, but certainly I'm glad to get some support. :)

**Comment by dankamongmen** [comment]
> ```
> // Takes ownership of the ncplane 'n', which will be destroyed by
> // ncprogbar_destroy(). The progress bar is initially at 0%.
> API ALLOC struct ncprogbar* ncprogbar_create(struct ncplane* n, const ncprogbar_options* opts)
>   __attribute__ ((nonnull (1)));
> ```
> What on earth are all these fringes around it?

https://gcc.gnu.org/onlinedocs/gcc/Function-Attributes.html

`#define API __attribute__((visibility("default")))`

https://gcc.gnu.org/wiki/Visibility
https://akkadia.org/drepper/dsohowto.pdf

`#define ALLOC __attribute__((malloc)) __attribute__((warn_unused_result))`

> Attribute malloc indicates that a function is malloc-like, i.e., that the pointer P returned by the function cannot alias any other pointer valid when the function returns, and moreover no pointers to valid objects occur in any storage addressed by P. In addition, the GCC predicts that a function with the attribute returns non-null in most cases. Independently, the form of the attribute with one or two arguments associates deallocator as a suitable deallocation function for pointers returned from the malloc-like function. ptr-index denotes the positional argument to which when the pointer is passed in calls to deallocator has the effect of deallocating it. Using the attribute with no arguments is designed to improve optimization by relying on the aliasing property it implies. Functions like malloc and calloc have this property because they return a pointer to uninitialized or zeroed-out, newly obtained storage. However, functions like realloc do not have this property, as they may return pointers to storage containing pointers to existing objects. Additionally, since all such functions are assumed to return null only infrequently, callers can be optimized based on that assumption. Associating a function with a deallocator helps detect calls to mismatched allocation and deallocation functions and diagnose them under the control of options such as -Wmismatched-dealloc. It also makes it possible to diagnose attempts to deallocate objects that were not allocated dynamically, by -Wfree-nonheap-object. To indicate that an allocation function both satisifies the nonaliasing property and has a deallocator associated with it, both the plain form of the attribute and the one with the deallocator argument must be used. The same function can be both an allocator and a deallocator. Since inlining one of the associated functions but not the other could result in apparent mismatches, this form of attribute malloc is not accepted on inline functions. For the same reason, using the attribute prevents both the allocation and deallocation functions from being expanded inline.

> The warn_unused_result attribute causes a warning to be emitted if a caller of the function with this attribute does not use its return value. This is useful for functions where not checking the result is either a security problem or always a bug, such as realloc.

> The nonnull attribute may be applied to a function that takes at least one argument of a pointer type. It indicates that the referenced arguments must be non-null pointers. For instance, the declaration:
```c
extern void *
my_memcpy (void *dest, const void *src, size_t len)
        __attribute__((nonnull (1, 2)));
```
> causes the compiler to check that, in calls to my_memcpy, arguments dest and src are non-null. If the compiler determines that a null pointer is passed in an argument slot marked as non-null, and the -Wnonnull option is enabled, a warning is issued. See Warning Options. Unless disabled by the -fno-delete-null-pointer-checks option the compiler may also perform optimizations based on the knowledge that certain function arguments cannot be null. In addition, the -fisolate-erroneous-paths-attribute option can be specified to have GCC transform calls with null arguments to non-null functions into traps. See Optimize Options.

**Comment by tomek-szczesny** [comment]
Awesome! Thanks a bunch! Googling "ALLOC C" isn't quite as helpful indeed :D

**Comment by dankamongmen** [comment]
i would definitely prefer that your VT100 translation stuff be distinct from the widget piece, so they can be freely used by other stuff (they're going to get wired up to `ncsubprocess`, remember)

**Comment by tomek-szczesny** [comment]
I guess I won't be making widget after all.
