### ISSUE TITLE
Parsing SGR parameters

### ISSUE THREAD

**Issue by tomek-szczesny** [tomek-szczesny/notcurses-vt-proto#3]
It works for color support, but is already getting messy and inflexible.

- Some SGRs have question marks at the beginning of a parameters list
- Arguments might be empty, indicating "default value", which may be 0 or 1, depending on a function.
- As of today, arguments list is being copied to internal buffer with fixed length (ouch)

I think this should be handled very differently!
- Figure out if SGR is complete ("final byte" has been identified)
- If it is, there's no stopping us from introducing more states instead of mammoth switch {}
- Make an elegant parser that fetches consecutive numbers and symbols straight outta buffer
- Assign negative ints to special cases:
 -1 to empty (default value)
 -2 to question mark
 (may be easily expanded in the future if needed)

**Comment by o-sdn-o** [comment]
> Assign negative ints to special cases:
-1 to empty (default value)
-2 to question mark
(may be easily expanded in the future if needed)

Despite the fact that the standard prohibits the use of the '-' sign in CSI sequences, I use it. Negative parameters are needed for example when tracking the mouse outside the screen boundaries. 

https://www.youtube.com/watch?v=nIujUzl30NI

I break this convention if the terminal supports it (responds to the mode `\e[?10060h`)

**Comment by o-sdn-o** [comment]
> Arguments might be empty, indicating "default value", which may be 0 or 1, depending on a function.

It is also necessary to distinguish between subparameters separated by colons instead of semicolons.

E.g.
`CSI param1 : sub_arg ; param2 : sub_arg1 : sub_arg2 final_byte`

**Comment by tomek-szczesny** [comment]
That's an interesting thought, that negative values might actually be valid arguments. However I think I'll focus on implementing at least a subset of standard before expanding it...

Could you point me at the example of a command that uses subparameters? I've never heard of that. I only heard that Linux terminal prefers colons over semicolons.

**Comment by o-sdn-o** [comment]
> Could you point me at the example of a command that uses subparameters?

- True color SGR https://gist.github.com/XVilka/8346728
- Styled underline https://sw.kovidgoyal.net/kitty/protocol-extensions.html?highlight=sequences#colored-and-styled-underlines

**Comment by o-sdn-o** [comment]
The [DEC STD070 document](https://archive.org/details/bitsavers_decstandar0VideoSystemsReferenceManualDec91_74264381) can be useful when creating your own vt-parser, aka "the bible".

**Comment by tomek-szczesny** [comment]
Hm, so in case of true color SGR the safest approach is to support colons **and** semicolons as delimiters, and the kitty extensions, since are kitty-specific, I find completely optional.
Personally I'm not a fan of expanding these already messy signalling schemes. I'd stick to de facto standard of xterm for now. 

Oh yes, I found "the bible" yesterday and it's very helpful, but didn't provide any explanation what exactly "autowrap" does, so that wasn't love from the first sight. :)

**Comment by tomek-szczesny** [comment]
I ended up parsing numbers with delimiters and left out question mark to be parsed some other way. This is still a mess, but got much better, and should be good enough for now.
